# Generated by Django 4.0 on 2021-12-19 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='bio',
            field=models.CharField(blank=True, max_length=280, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='user',
            name='facebook_account',
            field=models.URLField(blank=True, max_length=255, null=True, verbose_name='Profile Facebook'),
        ),
        migrations.AlterField(
            model_name='user',
            name='github_account',
            field=models.URLField(blank=True, max_length=255, null=True, verbose_name='Profile GitHub'),
        ),
        migrations.AlterField(
            model_name='user',
            name='job_title',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name="Intitulé de l'emploi"),
        ),
        migrations.AlterField(
            model_name='user',
            name='linkedin_account',
            field=models.URLField(blank=True, max_length=255, null=True, verbose_name='Profile LinkedIn'),
        ),
        migrations.AlterField(
            model_name='user',
            name='location',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Localisation'),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(blank=True, max_length=255, verbose_name="Nom d'utilisateur"),
        ),
        migrations.AlterField(
            model_name='user',
            name='personal_url',
            field=models.URLField(blank=True, max_length=555, null=True, verbose_name='URL perso'),
        ),
        migrations.AlterField(
            model_name='user',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/', verbose_name='Photo de profile'),
        ),
        migrations.AlterField(
            model_name='user',
            name='short_bio',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='Petite description'),
        ),
        migrations.AlterField(
            model_name='user',
            name='twitter_account',
            field=models.URLField(blank=True, max_length=255, null=True, verbose_name='Profile Twitter'),
        ),
    ]
