# Generated by Django 4.0 on 2021-12-19 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notebooks', '0002_alter_notebook_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='notebook',
            name='vue',
            field=models.FileField(blank=True, upload_to='notebook/%Y/%m/%d/', verbose_name="Une version html du notebook pour l'affichage"),
        ),
    ]
