# Generated by Django 4.0 on 2021-12-19 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0002_alter_question_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='title',
            field=models.CharField(max_length=200, unique=True, verbose_name='Titre'),
        ),
    ]
