# Generated by Django 4.0 on 2021-12-19 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='verb',
            field=models.CharField(choices=[('L', 'À aimé'), ('C', 'À commenté'), ('F', 'À favorise'), ('A', 'À répondu'), ('W', 'À accepté'), ('E', 'À édite'), ('K', 'À aussi commenté'), ('I', "S'est connecté(e)"), ('O', "S'est déconnecté(e)"), ('V', 'Approuve'), ('S', 'À partagé'), ('U', "S'est inscrit(e)"), ('R', 'À répondu')], max_length=1),
        ),
    ]
